### ISSUE TITLE
Missing on Flathub.org

### ISSUE THREAD

**Issue by AsciiWolf** [flathub/com.github.micahflee.torbrowser-launcher#1]
Tor Browser Launcher is missing on the Flathub.org website for some reason. It is showing fine in GNOME Software.

**Comment by bilelmoussaoui** [comment]
Probably a missing launchable tag.

**Comment by AsciiWolf** [comment]
I am not sure if the missing launchable tag is what causes this issue. @barthalion Any idea?

**Comment by AsciiWolf** [comment]
@bilelmoussaoui Do you have an idea how to fix this? I have compared the original [AppData file](https://github.com/micahflee/torbrowser-launcher/blob/develop/share/metainfo/torbrowser.appdata.xml) with [OpenMW](https://github.com/flathub/org.openmw.OpenMW/blob/master/org.openmw.OpenMW.appdata.xml) from Flathub and the only real difference seems to be ` type="desktop"` in the _component_ tag.

**Comment by bilelmoussaoui** [comment]
You're right. The missing component type fallback to the default generic component which is not shown on Flathub frontend. Using desktop/desktop-application should fix it
