### ISSUE TITLE
Verify the Flatpak

### ISSUE THREAD

**Issue by AsciiWolf** [flathub/com.github.micahflee.torbrowser-launcher#134]
Since the Tor Browser Launcher Flatpak is an official one, it would be great if it could be verified.

Here are more details about verified apps: https://flathub.org/about

/cc @micahflee

**Comment by Perkolator** [comment]
> Tor Browser Launcher Flatpak is an official one

Is this flatpak official? I can't find any mention or link on the torproject.org webpage.

**Comment by AsciiWolf** [comment]
This is not an official Tor Project project, however it is an official Flatpak for the [Tor Browser Launcher](https://github.com/micahflee/torbrowser-launcher) project. ;-)

**Comment by Perkolator** [comment]
Ok, this flatpak is 3rd party and has nothing to do with Tor Project/Browser.

**Comment by AsciiWolf** [comment]
@micahflee It looks like it can be verified by logging in on Flathub.org using your GitHub account and clicking "Login provider verification" in [the Flatpak developer settings](https://flathub.org/apps/manage/com.github.micahflee.torbrowser-launcher).

**Comment by micahflee** [comment]
Verified!

![Screenshot from 2023-07-18 10-21-39](https://github.com/flathub/com.github.micahflee.torbrowser-launcher/assets/156128/38fc20e3-1e41-4cf2-900b-ea3665c097cb)
