### ISSUE TITLE
Uninstall leaves files behind

### ISSUE THREAD

**Issue by Perkolator** [flathub/com.github.micahflee.torbrowser-launcher#138]
Uninstalled the flatpak without an error but the `$HOME/.var/app/com.github.micahflee.torbrowser-launcher` folder still has all(?) the files, `423 items, totalling 386,4 MiB.`

Bug?

Is it safe to remove this folder manually?

**Comment by AsciiWolf** [comment]
This is intended. Yes, it is safe to remove the directory manually.
