### ISSUE TITLE
Error: "SIGNATURE VERIFICATION FAILED!"

### ISSUE THREAD

**Issue by TheEvilSkeleton** [flathub/com.github.micahflee.torbrowser-launcher#14]
I just installed Tor a couple of minutes ago, and I got the following error:

![image](https://user-images.githubusercontent.com/50847364/102962193-49ecf480-44b4-11eb-8924-6edb8281427d.png)

**Comment by AsciiWolf** [comment]
Ouch. You are right, I have just been able to reproduce this issue.

Here is an upstream ticket: https://github.com/micahflee/torbrowser-launcher/issues/543

**Comment by AsciiWolf** [comment]
https://github.com/micahflee/torbrowser-launcher/issues/534#issuecomment-748649071

**Comment by nickavem** [comment]
Can reproduce same issue in flatpak, but not on natively installed rpm in podman...

**Comment by AsciiWolf** [comment]
Hmm, that's strange. I will try to further investigate this issue in upcoming days.

**Comment by AsciiWolf** [comment]
So, I have tested non-Flatpak Tor Browser Launcher on Ubuntu 20.04 (older version) and Fedora 33 (latest 0.3.3) and can confirm that the issue really seems to happen **only** with the Flatpak version.

@micahflee Do you have any idea what could cause this?

**Comment by AsciiWolf** [comment]
I have tried looking at it with strace, but still no luck.

**Comment by AsciiWolf** [comment]
As a workaround, I have manually added a patch to update the shipped Tor Browser developers key (see #16). It does not fix the key auto update mechanism that does not work in a Flatpak version of Tor Browser Launcher for some reason. However, it at least solves the current situation with the key being expired.
