### ISSUE TITLE
How to use "tor" through this bundle?

### ISSUE THREAD

**Issue by firefoxlover** [flathub/com.github.micahflee.torbrowser-launcher#168]
I would think the "tor" binary, managing the routing should be available somewhere in the bundle, but I was not able to find it.

It would be nice to have it accessible, to use CLI tools like SSH over Tor with this tool.

**Comment by AsciiWolf** [comment]
This Flatpak is based on [Tor Browser](https://www.torproject.org/download/). You can try running `flatpak run --command=sh com.github.micahflee.torbrowser-launcher`, then cd into `~/.var/app/com.github.micahflee.torbrowser-launcher/data/torbrowser/tbb/x86_64/tor-browser/Browser/TorBrowser/Tor` and run the `tor` binary, however this is unsupported and out-of-scope of this Flatpak's intended use-case. I am closing this ticket.

**Comment by AsciiWolf** [comment]
Anyway, packaging just a tor client as a Flatpak could be a good idea. Feel free to prepare the Flatpak - I can provide some help if you want. :-)
