### ISSUE TITLE
Does not work (oob) on Wayland

### ISSUE THREAD

**Issue by egrath** [flathub/com.github.micahflee.torbrowser-launcher#17]
The Flatpak build does not work OOB on devices which are using Wayland as their display protocol, as the necessary permission is not set in the manifest.

**Solution**:
Add the following to the finish-args:
```
--socket=wayland
```

**Workaround**
Run:
```
flatpak override --user --socket=wayland com.github.micahflee.torbrowser-launcher
```

**Comment by AsciiWolf** [comment]
Please also try `--nosocket=x11` to disable X11 after enabling the Wayland socket. Last time I tried this, Tor Browser was not able to run natively on Wayland. With `--socket=x11`, it runs on Wayland using XWayland. If it does not work on Wayland, there is no point in enabling the Wayland socket.

**Comment by egrath** [comment]
Without the permission for the Wayland socket, the application does not even start on XWayland. Output with the default permissions on a Wayland system:
```
Failed to create wl_display (No such file or directory)
qt.qpa.plugin: Could not load the Qt platform plugin "wayland" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, xcb.
```

**Comment by AsciiWolf** [comment]
Hmm, it works fine on both my Fedora systems with GNOME on Wayland. What desktop environment do you have?

**Comment by egrath** [comment]
Endless OS (latest, 3.9.1)

**Comment by AsciiWolf** [comment]
This seems to be a bug in the Endless OS XWayland implementation.

**Comment by egrath** [comment]
OK, i open a Bug for them, thanks for the investigation on other OS.
