### ISSUE TITLE
Signature verification failed

### ISSUE THREAD

**Issue by Toastymuffin68** [flathub/com.github.micahflee.torbrowser-launcher#172]
While trying to install on Kali Linux i keep getting a signature verification failed.
613188FC5BE2176E3ED54901E53D989A9E2D47BF:key expired.
What are my options?

**Comment by AsciiWolf** [comment]
It looks like it actually is a Tor keyserver issue, not this Flatpak or a torbrowser-launcher one. See this comment: https://github.com/micahflee/torbrowser-launcher/issues/700#issuecomment-1727392723

**Comment by AsciiWolf** [comment]
Upstream is currently working on a fix.

**Comment by AsciiWolf** [comment]
The issue has been fixed by upstream. :-)

**Comment by Gullixus** [comment]
gpg: key 4E2C6E8793298290: public key "Tor Browser Developers (signing key) <torbrowser@torproject.org>" imported gpg: Total number processed: 1 gpg: imported: 1 pub rsa4096 2014-12-15 [C] [expires: 2025-07-21] EF6E286DDA85EA2A4BA7DE684E2C6E8793298290 uid [ unknown] Tor Browser Developers (signing key) <torbrowser@torproject.org> sub rsa4096 2018-05-26 [S] [expires: 2020-12-19]

**Comment by AsciiWolf** [comment]
@Gullixus Please, create a separate ticket for this. It looks like that your torbrowser-launcher version is most likely too old.
