### ISSUE TITLE
Doesn't run under "full wayland"

### ISSUE THREAD

**Issue by IlgazC** [flathub/com.github.micahflee.torbrowser-launcher#18]
Hello

I use openSUSE Tumbleweed with "full wayland" session enabled. When I launch the application I see the following message in console:
 flatpak run com.github.micahflee.torbrowser-launcher

Failed to create wl_display (No such file or directory)
qt.qpa.plugin: Could not load the Qt platform plugin "wayland" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, xcb.

**Comment by AsciiWolf** [comment]
Hello,

thanks for opening this ticket. Yeah, Tor Browser unfortunately does not support Wayland. When I last tried it (disabled `x11` socket and enabled `wayland` socket), it did not run at all. This is the reason why this Flatpak does not have the wayland socket enabled. I am not happy with it (X11 security is bad when compared to Wayland), but at least it runs fine using XWayland. Maybe there is some env variable to make Tor Browser run natively on Wayland (the Firefox version they are using as a base should support Wayland), but I was not able to find any.

**Comment by AsciiWolf** [comment]
```
Launching './Browser/start-tor-browser --detach'...
Tor Browser must be run within the X Window System.
Exiting.
```

It looks like that the Tor Browser itself does not support Wayland.

**Comment by Cortex65** [comment]
I don't know why this should be the case.  Tor Browser is based upon Firefox 78 ESR and Wayland support (and Flatpak support) both landed in Firefox before 78.  This must be an upstream build-time decision not lack of support in Firefox.

FWIW Tor Browser Alpha (as of this writing: 10.5a16) works Wayland-native and both branches are based upon Firefox 78.11.0esr.

Perhaps a way forward is to package the alpha into a different flathub branch.

**Comment by AsciiWolf** [comment]
As you can see in my previous message, it seems to be a X11 server check in the Tor Browser startup script. This needs to be fixed in Tor Browser upstream, not Tor Browser Launcher. You can probably try reporting it [here](url). Afterwards, please send the upstream ticket url as a comment to this ticket. Thanks!

**Comment by Cortex65** [comment]
I'm waiting for the account to get approved for gitlab there.  In the meantime, here's how I worked around it.

`
--- a/Browser/start-tor-browser	1999-12-31 16:00:00.000000000 -0800
+++ b/Browser/start-tor-browser	2021-01-12 06:28:56.434562745 -0800
@@ -7,10 +7,12 @@
 
 complain_dialog_title="Tor Browser"
 
-# First, make sure DISPLAY is set.  If it isn't, we're hosed; scream
-# at stderr and die.
-if [ "x$DISPLAY" = "x" ]; then
-    echo "$complain_dialog_title must be run within the X Window System." >&2
+# First, make sure DISPLAY or WAYLAND_DISPLAY is set.  If it isn't, we're 
+# hosed; scream at stderr and die.
+if [ "x$DISPLAY" != "x" ] || [ "x$WAYLAND_DISPLAY" != "x" ]; then
+    : # do nothing
+else
+    echo "$complain_dialog_title must be run within the X Window System or Wayland." >&2
     echo "Exiting." >&2
     exit 1
 fi
`

**Comment by Cortex65** [comment]
> I'm waiting for the account to get approved for gitlab there. In the meantime, here's how I worked around it.

also, outside of that script:

MOZ_ENABLE_WAYLAND=1

I'm not sure if that requirement has been dropped by more recent Firefox versions, but I'll have to add it to the script for completeness.

**Comment by Cortex65** [comment]
Have made a change that should work for any current Tor Browser build, and corresponding merge request upstream.

https://gitlab.torproject.org/tpo/applications/tor-browser-build/-/merge_requests/303

**Comment by travankor** [comment]
Don't you also need to package `libmozwayland.so` as well? Can you check about:support that it shows wayland for windowing system?

**Comment by AsciiWolf** [comment]
Flatpak support for Tor Browser is now available in upstream. I will update the Flatpak to use it.

**Comment by Cortex65** [comment]
10.5 release does not have the changed 'start-tor-browser' to check for/enable Wayland.

@travankor I'm not very familiar with how flatpak works, but I believe you'd need to explicitly pass this to flatpak at runtime.  Having it in your shell environment is not enough by itself, I don't think.

**Comment by AsciiWolf** [comment]
@Cortex65 It looks like your MR was still not merged. :-/
