### ISSUE TITLE
Tor browser in Sandbox environment

### ISSUE THREAD

**Issue by Sukhman723** [flathub/com.github.micahflee.torbrowser-launcher#19]
Is it safe to run tor browser installed via flathub.
I've found in this post that sandboxing is limited only tor browser itself, and it will not sandbox the tabs or websites.

**Comment by AsciiWolf** [comment]
It should theoretically be much safer than running Tor Browser directly, without the Flatpak sandbox. As far as I know, tabs/websites sandboxing (isolation) is unfortunately not supported by Tor Browser.

**Comment by Sukhman723** [comment]
It means it is safe then, huh.

Edit: sorry I forgot to give you this [link](https://gitlab.torproject.org/tpo/applications/tor-browser/-/issues/40328) in which I've found about using tor browser in sandbox environment.

**Comment by AsciiWolf** [comment]
Hmm, interesting. I am not aware of any tab isolation api in Tor Browser that uses low-level things like special kernel syscalls, not working in Flatpak.

**Comment by Sukhman723** [comment]
In the above link some guys were talking about using **_flatpak-spawn_** which allows sandboxing within the flatpak app. This is done with the Firefox flatpak, but we need to apply patches

**Comment by AsciiWolf** [comment]
The _flatpak-spawn_ command is not about sandboxing, but actually about the exact opposite: Bypassing the Flatpak sandbox.

**Comment by Sukhman723** [comment]
I really don't know about this command but what I want to know about it is that _**Can it be used with flatpak to enhance its sandboxing capabilities?**_

**Comment by AsciiWolf** [comment]
What they probably meant is bypassing the Flatpak sandbox so they can use their own sandboxing api (if there is any) or their AppArmor rules. But this would go against the purpose of the Tor Browser Flatpak and would depend on system things outside of Flatpak to work properly. For example, AppArmor is used only on some Linux distributions like Ubuntu. Also, as I said, I am not sure whether there really is any "isolation api". The comment you linked does not seem to be from a Tor Browser developer.

There is no point in discussing this thing any further, sorry.

**Comment by nidamanx** [comment]
Hi, is there a good way to check if sandboxing is really working here?
if I choose "Open File..." from TOR Browser, I can see all files in al computer (not only in home). And I can open many of them.
I even tried Flatseal to have a better confinement, but still all files, seemly, are exposed.
Thanks

**Comment by AsciiWolf** [comment]
> if I choose "Open File..." from TOR Browser, I can see all files in al computer (not only in home). And I can open many of them.

This is handled by [Flatpak portals](https://github.com/flatpak/flatpak/wiki/Portals). You can look [here](https://github.com/flathub/com.github.micahflee.torbrowser-launcher/blob/master/com.github.micahflee.torbrowser-launcher.yaml#L10) to see the default Tor Browser Flatpak permissions.
