### ISSUE TITLE
Add OARS rating to AppData

### ISSUE THREAD

**Issue by AsciiWolf** [flathub/com.github.micahflee.torbrowser-launcher#2]
There are currently no [OARS](https://hughsie.github.io/oars/) metadata in the Tor Browser Launcher AppData file. It would be nice adding them.

**Comment by bilelmoussaoui** [comment]
How did the bot not complain about this?

**Comment by AsciiWolf** [comment]
Hmm, good question. :-) I will try to add OARS and launchable type this evening, maybe it will fix #1.

**Comment by barthalion** [comment]
appstream-glib disables certain checks if appdata doesn't specify `type="desktop"` in `<component>` tag. The application also misses release tag.

**Comment by AsciiWolf** [comment]
@barthalion Not anymore. :) I have added all the missing tags in a recent commit.

**Comment by barthalion** [comment]
We also catch appdata files like this now: https://github.com/barthalion/appstream-glib/commit/b275b200bc61de34c33ad1272db7714d987f701f
