### ISSUE TITLE
[RFE] aarch64 build

### ISSUE THREAD

**Issue by akallabeth** [flathub/com.github.micahflee.torbrowser-launcher#20]
Would be nice to have torbrowser on arm too

**Comment by AsciiWolf** [comment]
I can try building it, however I am not sure whether aarch64 is supported by torbrowser-launcher.

**Comment by iMonZ** [comment]
+1

**Comment by AsciiWolf** [comment]
Is aarch64 build of Tor Browser available? There seems to be only the x86_64 one on the [download page](https://www.torproject.org/download/).

**Comment by AsciiWolf** [comment]
I am afraid that the upstream aarch64 build of Tor Browser is unfortunately not available.
