### ISSUE TITLE
Download failing

### ISSUE THREAD

**Issue by yusufislam1** [flathub/com.github.micahflee.torbrowser-launcher#4]
I can't run tor browser

![20191018_224500](https://user-images.githubusercontent.com/56765980/67147471-c9be7400-f29d-11e9-8065-56a533f66b05.jpg)

**Comment by AsciiWolf** [comment]
Hmm, seems to be some connection problem. Do you still have the same issue?

**Comment by yusufislam1** [comment]
> Hmm, seems to be some connection problem. Do you still have the same issue?

yes

**Comment by AsciiWolf** [comment]
Does this issue still happen to you? If so, could you try removing the `~/.var/app/com.github.micahflee.torbrowser-launcher` directory and try it again?

**Comment by AsciiWolf** [comment]
I was not able to reproduce this issue. Feel free to reopen this ticket if you are still experiencing the issue.

**Comment by yusufislam1** [comment]
@AsciiWolf the problem had disappeared before ... but i am having trouble again ..

![2020-03-29 23-19-37 ekran görüntüsü](https://user-images.githubusercontent.com/56765980/77859763-d911f800-7213-11ea-8d1f-70ce45441c69.png)

**Comment by AsciiWolf** [comment]
Hmm, that's weird.

**Comment by yusufislam1** [comment]
Did the problem disappear? @AsciiWolf

**Comment by AsciiWolf** [comment]
I don't know. I was not able to reproduce this issue at all. Did it disappear for you?

**Comment by yusufislam1** [comment]
no :(

**Comment by yusufislam1** [comment]
@AsciiWolf What should I do to fix the problem?

**Comment by AsciiWolf** [comment]
I don't know, sorry. I have tried to reproduce this issue on multiple configurations/OSes, including Endless OS, and everything worked fine.

Did you try to remove the `~/.var/app/com.github.micahflee.torbrowser-launcher` directory as I suggested before? If so, maybe your ISP is blocking access to Tor for some reason. In that case, you can try launching "Tor Browser Launcher Settings", selecting another _Mirror_ from the list, then clicking _Save & Exit_ and launching Tor Browser again.

**Comment by yusufislam1** [comment]
How do I remove the directory in the row?

**Comment by AsciiWolf** [comment]
Open your file manager, open your home directory, show hidden files (I think _Ctrl + H_ is a keyboard shortcut for this), open _.var_, then open _app_, then select _com.github.micahflee.torbrowser-launcher_ and delete it.

**Comment by yusufislam1** [comment]
it didn't happen again. i had this problem before but i don't remember how i solved it @AsciiWolf

**Comment by wjt** [comment]
If you can reproduce this problem, you could check whether there is anything interesting in the system journal, right after you reproduce it. On Endless you can run `eos-diagnostics` in a Terminal window to generate a huge diagnostic file, including the journal.

> If so, maybe your ISP is blocking access to Tor for some reason. In that case, you can try launching "Tor Browser Launcher Settings", selecting another _Mirror_ from the list, then clicking _Save & Exit_ and launching Tor Browser again.

Did you try doing this?

If it is always this particular URL from the screenshots `https://aus1.torproject.org/torbrowser/update_3/release/Linux_x86_64-gcc3/x/en-US` you could try opening that in another web browser and see what you get.

**Comment by yusufislam1** [comment]
@wjt I did what he said and uploaded a file to the files section. It's like my 3-day history but I don't understand yet. what you say is explained in more detail here https://support.endlessm.com/hc/en-us/articles/208416346-How-do-I-make-a-debug-log-of-Endless-OS-

->I did the quote text but I couldn't find the 'mirror' section

https://aus1.torproject.org/torbrowser/update_3/release/Linux_x86_64-gcc3/x/en-US when i scan this link i came across this image
![2020-04-09 05-01-54 ekran görüntüsü](https://user-images.githubusercontent.com/56765980/78850317-958f6900-7a1f-11ea-9c72-4819f0803f6e.png)

**Comment by yusufislam1** [comment]
@AsciiWolf  @wjt  will anyone be interested?  I say I need this

**Comment by AsciiWolf** [comment]
Sorry, I am too busy with other stuff I work on lately and I was not able to reproduce your issue at all.

**Comment by yusufislam1** [comment]
I deleted the hidden files previously unconsciously. Could it be due to this?  @AsciiWolf @wjt

**Comment by LeandroStanger** [comment]
**Use the command:**
```
flatpak update --appstream && flatpak update -y
flatpak run com.github.micahflee.torbrowser-launcher --reset
flatpak run com.github.micahflee.torbrowser-launcher
```

**Comment by yusufislam1** [comment]
It did not work... it didn't work on my first try... I wrote the second command on my second try and this is the visual @LeandroStanger 

![2020-04-16 04-36-49 ekran görüntüsü](https://user-images.githubusercontent.com/56765980/79405188-5f606500-7f9c-11ea-9c54-3bc97af12a39.png)

**Comment by yusufislam1** [comment]
it didn't work on my first try... In my second try I entered the second command and encountered this
@LeandroStanger 
![2020-04-16 04-36-49 ekran görüntüsü](https://user-images.githubusercontent.com/56765980/79444542-f7357180-7fe3-11ea-8147-c6602c039b9c.png)

**Comment by LeandroStanger** [comment]
**Use the command:**
```
sudo flatpak repair
```

**Comment by yusufislam1** [comment]
@LeandroStanger  didn't work again... I repeated the commands...


![2020-04-16 17-59-56 ekran görüntüsü](https://user-images.githubusercontent.com/56765980/79472292-53ac8700-800c-11ea-8054-e0d66ae6e4d1.png)
![2020-04-16 18-01-31 ekran görüntüsü](https://user-images.githubusercontent.com/56765980/79472318-5a3afe80-800c-11ea-8f3e-4100f627f41e.png)

**Comment by yusufislam1** [comment]
@wjt @LeandroStanger  Someone has helped me on Telegram before... one of you... If the messages were not deleted, can you send the commands in the messages again?

**Comment by yusufislam1** [comment]
@wjt @AsciiWolf @LeandroStanger I want to replace the Endless Operating System... I want to install Kali Linux... Could you help...

**Comment by AsciiWolf** [comment]
No, we can't. This is an off topic discussion here, sorry.

**Comment by bilelmoussaoui** [comment]
I'm going to go ahead and lock this issue
