### ISSUE TITLE
Signature verification failed

### ISSUE THREAD

**Issue by offlinehacker** [flathub/com.github.micahflee.torbrowser-launcher#8]
When downloading torbrowser and checking signature i get following error: https://github.com/micahflee/torbrowser-launcher/issues/485

Solution was to replace key manually in `/var/lib/flatpak/app/com.github.micahflee.torbrowser-launcher/x86_64/stable/active/files/share/torbrowser-launcher/tor-browser-developers.asc`: https://github.com/micahflee/torbrowser-launcher/issues/485#issuecomment-684505156

**Comment by AsciiWolf** [comment]
Thanks for reporting this issue and the possible workaround! Let's hope that this will get fixed soon upstream so I can update this Flatpak. If not, I will try to prepare a patch myself.

**Comment by offlinehacker** [comment]
Thanks!
